stages:
  train_load_data:
    cmd: python3 src/pipeline_01_data_preperation.py --config=config/params.yaml --stage=train
    deps:
    - src/pipeline_01_data_preperation.py
    outs:
    - data/processed/preprocessed_data_train/preprocessed_train.csv
  
  split_data:
    cmd: python src/pipeline_02_data_split.py --config=config/params.yaml
    deps:
    - src/pipeline_01_data_preperation.py
    - data/processed/preprocessed_data_train/preprocessed_train.csv
    outs:
    - data/processed/preprocessed_data_split/preprocessed_train.csv
    - data/processed/preprocessed_data_split/preprocessed_dev.csv