stages:
  train_load_data:
    cmd: python3 src/pipeline_01_data_preperation.py --config=config/params.yaml --stage=train
    deps:
    - src/pipeline_01_data_preperation.py
    - data/raw/wafer-dataset-main/Training_Batch_Files/
    outs:
    - data/processed/preprocessed_data_train