base:
  project: Wafer-Quality-Project
  random_state: 42
  target_col: Output

data_source:
  base_path: data/raw/collate-dataset
  train: 
    raw_files:  data/raw/wafer-dataset-main/Training_Batch_Files
    final_file: train_raw_wafer.csv
  pred :
    raw_files: data/raw/wafer-dataset-main/Prediction_Batch_Files
    final_file: pred_raw_wafer.csv

data_preprocessing:
  train: 
    base_dir:  data/processed/preprocessed_data_train
    filepath: train_preprocessed_wafer.csv
  pred: 
    base_dir:  data/processed/preprocessed_data_pred
    filepath: pred_preprocessed_wafer.csv


  KNNImputer: 
    n_neighbors: 3 
    weights: uniform
    missing_values: nan

  KMeansClustering:
    init: k-means++
    n_cluster_max: 11
    KneeLocator: 
      curve: convex
      direction: decreasing
    
split_data:
  base_path: data/processed/preprocessed_data_train_split
  train_path: preprocessed_train_wafer.csv
  dev_path: preprocessed_dev_wafer.csv
  test_size: 0.2

artifacts_dir: 
  general: models
  mlflow: models/mlflow_artifacts


training:
  random_forest:
    cv: 5
    verbose: 3
    param_grid:
      n_estimators: 
        - 10
        - 50
        - 100
        - 130 
      criterion: 
        - gini
        - entropy
      max_depth: 
        - 2
        - 4
      max_features: 
        - auto
        - log2
  xg_boost:
    cv: 5
    verbose: 3
    param_grid:
      learning_rate: 
        - 0.5
        - 0.1
        - 0.01
        - 0.001
      max_depth: 
        - 3
        - 5
        - 10
        - 20
      n_estimators: 
        - 10
        - 50
        - 100
        - 200

saved_models:
  model_dir: models

reports:
  params: report/params.json
  scores: report/scores.json